-- RecorderLocalScript.lua
-- Coloque este LocalScript em StarterPlayerScripts (ou equivalente cliente)

local Players = game:GetService("Players")
local UserInputService = game:GetService("UserInputService")
local RunService = game:GetService("RunService")
local HttpService = game:GetService("HttpService")

local player = Players.LocalPlayer
local playerGui = player:WaitForChild("PlayerGui")

-- UI
local screenGui = Instance.new("ScreenGui")
screenGui.Name = "ActionRecorderGui"
screenGui.ResetOnSpawn = false
screenGui.Parent = playerGui

local mainFrame = Instance.new("Frame")
mainFrame.AnchorPoint = Vector2.new(0.5, 0)
mainFrame.Position = UDim2.new(0.5, 0, 0.02, 0)
mainFrame.Size = UDim2.new(0, 360, 0, 40)
mainFrame.BackgroundTransparency = 0.4
mainFrame.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
mainFrame.BorderSizePixel = 0
mainFrame.Parent = screenGui

local toggleBtn = Instance.new("TextButton")
toggleBtn.Size = UDim2.new(0, 120, 1, 0)
toggleBtn.Position = UDim2.new(0, 6, 0, 6)
toggleBtn.Text = "Start Recording"
toggleBtn.Parent = mainFrame

local exportBtn = Instance.new("TextButton")
exportBtn.Size = UDim2.new(0, 120, 1, 0)
exportBtn.Position = UDim2.new(0, 132, 0, 6)
exportBtn.Text = "Show Code"
exportBtn.Parent = mainFrame

local statusLabel = Instance.new("TextLabel")
statusLabel.Size = UDim2.new(0, 106, 1, 0)
statusLabel.Position = UDim2.new(0, 258, 0, 6)
statusLabel.BackgroundTransparency = 1
statusLabel.TextColor3 = Color3.fromRGB(220,220,220)
statusLabel.Text = "Idle"
statusLabel.TextXAlignment = Enum.TextXAlignment.Center
statusLabel.Parent = mainFrame

-- Output window (hidden until export)
local outputFrame = Instance.new("Frame")
outputFrame.AnchorPoint = Vector2.new(0.5, 0.5)
outputFrame.Position = UDim2.new(0.5, 0.5, 0.5, 0)
outputFrame.Size = UDim2.new(0, 700, 0, 420)
outputFrame.BackgroundColor3 = Color3.fromRGB(10,10,10)
outputFrame.BorderSizePixel = 0
outputFrame.Visible = false
outputFrame.Parent = screenGui

local closeBtn = Instance.new("TextButton")
closeBtn.Size = UDim2.new(0, 80, 0, 30)
closeBtn.Position = UDim2.new(1, -90, 0, 10)
closeBtn.Text = "Close"
closeBtn.Parent = outputFrame

local copyBtn = Instance.new("TextButton")
copyBtn.Size = UDim2.new(0, 80, 0, 30)
copyBtn.Position = UDim2.new(1, -180, 0, 10)
copyBtn.Text = "Copy"
copyBtn.Parent = outputFrame

local codeBox = Instance.new("TextBox")
codeBox.Position = UDim2.new(0, 10, 0, 50)
codeBox.Size = UDim2.new(1, -20, 1, -60)
codeBox.TextWrapped = false
codeBox.TextXAlignment = Enum.TextXAlignment.Left
codeBox.TextYAlignment = Enum.TextYAlignment.Top
codeBox.Font = Enum.Font.Code
codeBox.TextSize = 14
codeBox.ClearTextOnFocus = false
codeBox.Text = ""
codeBox.MultiLine = true
codeBox.Parent = outputFrame
codeBox.TextEditable = false
codeBox.TextColor3 = Color3.fromRGB(230,230,230)
codeBox.BackgroundColor3 = Color3.fromRGB(18,18,18)
codeBox.BorderSizePixel = 0

-- Recorder state
local recording = false
local startTime = 0
local actions = {} -- list of {t=seconds_since_start, type="...", ...}
local sampleInterval = 0.18
local lastSample = 0

local function now()
	return os.clock() - startTime
end

local function pushAction(tbl)
	tbl.t = now()
	table.insert(actions, tbl)
end

-- Helpers for serializing to Lua code
local function isArray(t)
	local n = 0
	for k,_ in pairs(t) do
		if type(k) ~= "number" then return false end
		n = n + 1
	end
	return n == #t
end

local function serializeValue(v)
	local t = typeof(v)
	if t == "number" then
		return tostring(v)
	elseif t == "string" then
		return string.format("%q", v)
	elseif t == "boolean" then
		return v and "true" or "false"
	elseif t == "Vector3" then
		return ("Vector3.new(%s,%s,%s)"):format(v.X, v.Y, v.Z)
	elseif t == "CFrame" then
		local x,y,z = v:ToOrientation()
		return ("CFrame.new(%s,%s,%s) * CFrame.fromEulerAnglesXYZ(%s,%s,%s)"):format(v.X, v.Y, v.Z, x, y, z)
	elseif t == "table" then
		-- recurse
		local parts = {}
		local is_arr = isArray(v)
		if is_arr then
			for i=1,#v do
				table.insert(parts, serializeValue(v[i]))
			end
			return "{" .. table.concat(parts, ",") .. "}"
		else
			for k,val in pairs(v) do
				local key
				if type(k) == "string" and k:match("^%a[%w_]*$") then
					key = k
				else
					key = "[" .. serializeValue(k) .. "]"
				end
				table.insert(parts, key .. "=" .. serializeValue(val))
			end
			return "{" .. table.concat(parts, ",") .. "}"
		end
	else
		-- fallback for userdata/enums: tostring
		return string.format("%q", tostring(v))
	end
end

local function actionsToLua(a)
	local parts = {}
	for i,act in ipairs(a) do
		parts[i] = serializeValue(act)
	end
	return "{\n" .. table.concat(parts, ",\n") .. "\n}"
end

-- Replay template (simple)
local function buildReplayScript(a)
	local header = [[
-- Replay script generated by RecorderLocalScript
-- Use in a LocalScript: require the actions table and call replayActions(player.Character)
local HttpService = game:GetService("HttpService")
]]
	local actionsLua = "local actions = " .. actionsToLua(a) .. "\n\n"

	local body = [[
local function applyVector(v)
	return v -- v is already Vector3/CFrame in this representation
end

local function replayActions(character)
	if not character then return end
	local hrp = character:FindFirstChild("HumanoidRootPart")
	local humanoid = character:FindFirstChildOfClass("Humanoid")
	local start = tick()
	local i = 1
	while i <= #actions do
		local act = actions[i]
		local delay = act.t - (tick() - start)
		if delay > 0 then
			task.wait(delay)
		end

		if act.type == "pos" and hrp then
			-- teleport to recorded position
			if act.pos then
				hrp.CFrame = CFrame.new(act.pos)
			end
		elseif act.type == "input" then
			-- inputs can't be simulated reliably on Roblox client in all cases.
			-- You can handle custom events here if desired.
			-- Example: print input
			print("Input:", act.inputType, act.key or act.button)
		elseif act.type == "mouse" then
			print("Mouse:", act.button, "target:", act.targetName)
		elseif act.type == "tool" then
			print("Tool event:", act.event, act.toolName)
		end

		i = i + 1
	end
end

return {
	actions = actions,
	replay = replayActions
}
]]
	return header .. actionsLua .. body
end

-- Input and tool tracking
local function connectTool(tool)
	if not tool then return end
	if tool:IsA("Tool") then
		local name = tool.Name
		if tool.Activated then
			tool.Activated:Connect(function()
				if recording then
					pushAction({type = "tool", event = "Activated", toolName = name})
				end
			end)
		end
		if tool.Equipped then
			tool.Equipped:Connect(function()
				if recording then
					pushAction({type = "tool", event = "Equipped", toolName = name})
				end
			end)
		end
		if tool.Unequipped then
			tool.Unequipped:Connect(function()
				if recording then
					pushAction({type = "tool", event = "Unequipped", toolName = name})
				end
			end)
		end
	end
end

local function watchCharacter(char)
	if not char then return end
	-- connect existing tools
	local backpack = player:FindFirstChildOfClass("Backpack")
	if backpack then
		for _,item in pairs(backpack:GetChildren()) do
			connectTool(item)
		end
	end
	-- connect tools in character
	for _,item in pairs(char:GetChildren()) do
		connectTool(item)
	end

	-- monitor future tools
	player:GetPropertyChangedSignal("Backpack"):Connect(function() end) -- noop to avoid lint; placeholder

	-- connect Character child added for tools
	char.ChildAdded:Connect(function(child)
		connectTool(child)
	end)
end

-- Character initial watch
if player.Character then
	watchCharacter(player.Character)
end
player.CharacterAdded:Connect(function(char)
	watchCharacter(char)
end)

-- Input events
UserInputService.InputBegan:Connect(function(input, gameProcessed)
	if not recording then return end
	if gameProcessed then return end
	local t = input.UserInputType.Name
	if input.UserInputType == Enum.UserInputType.Keyboard then
		pushAction({type="input", inputType="Key", key = input.KeyCode.Name, state = "began"})
	elseif input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.MouseButton2 then
		pushAction({type="input", inputType="MouseButton", button = input.UserInputType.Name, state = "began"})
	end
end)

UserInputService.InputEnded:Connect(function(input, gameProcessed)
	if not recording then return end
	if gameProcessed then return end
	local t = input.UserInputType.Name
	if input.UserInputType == Enum.UserInputType.Keyboard then
		pushAction({type="input", inputType="Key", key = input.KeyCode.Name, state = "ended"})
	elseif input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.MouseButton2 then
		pushAction({type="input", inputType="MouseButton", button = input.UserInputType.Name, state = "ended"})
	end
end)

-- Mouse clicks with target
local mouse = player:GetMouse()
mouse.Button1Down:Connect(function()
	if not recording then return end
	local target = mouse.Target
	local hit = nil
	pcall(function()
		if mouse.Hit then
			local p = mouse.Hit.p
			hit = {x = p.X, y = p.Y, z = p.Z}
		end
	end)
	pushAction({type="mouse", button="Button1", targetName = (target and target.Name) or nil, hit = hit})
end)

-- Position sampling
RunService.Heartbeat:Connect(function(dt)
	if not recording then return end
	lastSample = lastSample + dt
	if lastSample >= sampleInterval then
		lastSample = 0
		local char = player.Character
		if char and char:FindFirstChild("HumanoidRootPart") then
			local pos = char.HumanoidRootPart.Position
			pushAction({type="pos", pos = {x = pos.X, y = pos.Y, z = pos.Z}})
		end
	end
end)

-- UI actions
toggleBtn.MouseButton1Click:Connect(function()
	recording = not recording
	if recording then
		actions = {}
		startTime = os.clock()
		lastSample = 0
		statusLabel.Text = "Recording..."
		toggleBtn.Text = "Stop Recording"
		-- initial snapshot
		local char = player.Character
		if char and char:FindFirstChild("HumanoidRootPart") then
			local p = char.HumanoidRootPart.Position
			pushAction({type="pos", pos = {x = p.X, y = p.Y, z = p.Z}})
		end
	else
		statusLabel.Text = "Idle"
		toggleBtn.Text = "Start Recording"
	end
end)

exportBtn.MouseButton1Click:Connect(function()
	outputFrame.Visible = true
	codeBox.Text = buildReplayScript(actions)
	-- try copy to clipboard (only works in Studio/secure contexts)
	local ok, err = pcall(function()
		setclipboard(codeBox.Text)
	end)
	if ok then
		copyBtn.Text = "Copied"
		task.delay(1.5, function()
			if copyBtn and copyBtn.Parent then
				copyBtn.Text = "Copy"
			end
		end)
	end
end)

closeBtn.MouseButton1Click:Connect(function()
	outputFrame.Visible = false
end)

copyBtn.MouseButton1Click:Connect(function()
	local ok, err = pcall(function()
		setclipboard(codeBox.Text)
	end)
	if ok then
		copyBtn.Text = "Copied"
		task.delay(1.5, function()
			if copyBtn and copyBtn.Parent then
				copyBtn.Text = "Copy"
			end
		end)
	else
		warn("Cannot copy to clipboard:", err)
	end
end)
